version: '3.4' 

x-config: 
  - &nc_domain nc.utty.cloud
  - &nc_admin_login admin
  - &nc_admin_password eS5VHP9bPXyZiqg
  - &db_passwd VvvAaaTtewfav3
  - &db_database nextcloud
  - &db_user nextcloud
  - &le_mail doctor@equivalent.me
  

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    environment:
      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PASSWORD: *db_passwd
      MYSQL_DATABASE: *db_database
      MYSQL_USER: *db_user
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: *nc_domain
      LETSENCRYPT_HOST: *nc_domain
      LETSENCRYPT_EMAIL: *le_mail
      MYSQL_HOST: db
      MYSQL_PASSWORD: *db_passwd
      MYSQL_DATABASE: *db_database
      MYSQL_USER: *db_user
      NEXTCLOUD_ADMIN_USER: *nc_admin_login
      NEXTCLOUD_ADMIN_PASSWORD: *nc_admin_password
      NEXTCLOUD_TRUSTED_DOMAINS: *nc_domain
    restart: unless-stopped

volumes:
  nextcloud:

networks:
  nextcloud_network:
